### PR TITLE
Update Rust toolchain to nightly-2020-10-01

### PR DESCRIPTION
**Pull request by retrage**
This pull request updates the Rust toolchain to the latest (nightly-2020-10-01).
There are a few changes to get work:

1. Update x86_64 crate to 0.12:
It does not allow function pointers in constant functions
2. Use lazy_static:
It does not allow runtime calls in statics.

### CODE REVIEW

**Comment by josephlr** [comment]
I'd like to avoid depending on lazy_statoc if possible. I think we can fix this without using an external crate, I'll take a look

**Comment by josephlr** [comment]
Also, thanks @retrage for trying to fix this!!

I updated this PR to set the correct features on the `uart_16550` so that we don't need the lazy_static crate. I also changed the `const_item_mutation` to explicitly create the temporaries instead of just suppressing the warning.

**Review by josephlr — APPROVED** [review]

**Comment by rbradford** [comment]
Nice! Thanks.

**Comment by retrage** [comment]
Thanks!

**Pull request merged**
