### PR TITLE
AArch64: speed up paging and fix exception caused by atomic operation

### PR DESCRIPTION
**Pull request by jongwu**
There are some issues for rust firmware on arm64:

Two of them:

- use atomic instruction before mmu enabled may cause exception;
- page table creation takes too long;

To address above issues:

- Use atomic operation after MMU enabled;
- optimize page table creation algorithem;

### CODE REVIEW

**Comment by rbradford** [comment]
Please fix your formatting.

**Review by retrage — CHANGES_REQUESTED** [review]
Please remove the debug-related commit (d73060acd36cde57b707e2951b65a1cbf3e052be) from your PR, as it's too specific to your testing environment. If you want to keep the debug feature, you should provide scripts and documents so that other people can use it.

**Comment by jongwu** [comment]
> Please remove the debug-related commit ([d73060a](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/commit/d73060acd36cde57b707e2951b65a1cbf3e052be)) from your PR, as it's too specific to your testing environment. If you want to keep the debug feature, you should provide scripts and documents so that other people can use it.

OK, I will remove it currently.

**Comment by retrage** [comment]
@rbradford Yes, as it's listed on the tracking issue #198. I'd like to try vanilla Ubuntu cloud images with this PR changes.

**Pull request merged**
